version: "3.9"
services:
  db:
    image: postgres:16.2
    ports:
      - "54321:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=goooma_example
volumes:
  db-data:
